// Generated by gencpp from file dip/pid_driver.msg
// DO NOT EDIT!


#ifndef DIP_MESSAGE_PID_DRIVER_H
#define DIP_MESSAGE_PID_DRIVER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dip
{
template <class ContainerAllocator>
struct pid_driver_
{
  typedef pid_driver_<ContainerAllocator> Type;

  pid_driver_()
    : vel(0.0)
    , omega(0.0)  {
    }
  pid_driver_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , omega(0.0)  {
  (void)_alloc;
    }



   typedef double _vel_type;
  _vel_type vel;

   typedef double _omega_type;
  _omega_type omega;





  typedef boost::shared_ptr< ::dip::pid_driver_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dip::pid_driver_<ContainerAllocator> const> ConstPtr;

}; // struct pid_driver_

typedef ::dip::pid_driver_<std::allocator<void> > pid_driver;

typedef boost::shared_ptr< ::dip::pid_driver > pid_driverPtr;
typedef boost::shared_ptr< ::dip::pid_driver const> pid_driverConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dip::pid_driver_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dip::pid_driver_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dip::pid_driver_<ContainerAllocator1> & lhs, const ::dip::pid_driver_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel &&
    lhs.omega == rhs.omega;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dip::pid_driver_<ContainerAllocator1> & lhs, const ::dip::pid_driver_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dip

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dip::pid_driver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dip::pid_driver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dip::pid_driver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dip::pid_driver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dip::pid_driver_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dip::pid_driver_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dip::pid_driver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ce61d077baf56134fc51389b267fce5";
  }

  static const char* value(const ::dip::pid_driver_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ce61d077baf5613ULL;
  static const uint64_t static_value2 = 0x4fc51389b267fce5ULL;
};

template<class ContainerAllocator>
struct DataType< ::dip::pid_driver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dip/pid_driver";
  }

  static const char* value(const ::dip::pid_driver_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dip::pid_driver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vel\n"
"float64 omega\n"
;
  }

  static const char* value(const ::dip::pid_driver_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dip::pid_driver_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_driver_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dip::pid_driver_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dip::pid_driver_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "omega: ";
    Printer<double>::stream(s, indent + "  ", v.omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIP_MESSAGE_PID_DRIVER_H
